name: "Update mediawiki extensions"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '51 2 * * *'
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: ./modules/nixos-wiki/update-extensions.py ./modules/nixos-wiki/extensions.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Update zsh modules
          labels: merge-queue
